name: Supabase Ping

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'The command to run'
        required: true
  schedule:
    - cron: 0 9 * * 1,5 # Run every Monday and Friday at 9:00 AM

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install 

      - name: Ping Supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          node ./scripts/ping-supabase.js
